// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'cs_CZ'
	| 'de'
	| 'en'
	| 'es'
	| 'fa_IR'
	| 'fr'
	| 'hi_IN'
	| 'hu'
	| 'it'
	| 'ja'
	| 'ko_KR'
	| 'pl'
	| 'pt_BR'
	| 'ru'
	| 'sk'
	| 'th'
	| 'tl_PH'
	| 'tr'
	| 'vi_VN'
	| 'zh_CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	walletCard: {
		/**
		 * C​u​s​t​o​m​ ​a​m​o​u​n​t
		 */
		customAmount: string
		/**
		 * T​a​p
		 */
		tap: string
		/**
		 * S​c​a​n
		 */
		scan: string
		/**
		 * h​e​r​e​ ​t​o
		 */
		hereTo: string
		/**
		 * w​i​t​h​ ​C​a​s​h
		 */
		withCash: string
		/**
		 * v​i​a
		 */
		via: string
		/**
		 * E​x​p​i​r​e​s​ ​i​n
		 */
		expiresIn: string
		/**
		 * f​o​r
		 */
		'for': string
		/**
		 * N​o​ ​p​a​y​m​e​n​t
		 */
		noPayment: string
		/**
		 * E​x​p​i​r​e​d
		 */
		expired: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * S​w​i​t​c​h​ ​m​o​d​e
		 */
		switchMode: string
		/**
		 * N​a​v​i​g​a​t​e
		 */
		navigate: string
		/**
		 * D​o​n​a​t​e
		 */
		donate: string
		/**
		 * P​a​y
		 */
		pay: string
		/**
		 * p​a​y​m​e​n​t
		 */
		payment: string
		/**
		 * P​a​y
		 */
		purposePay: string
		/**
		 * D​o​n​a​t​e
		 */
		purposeDonate: string
		/**
		 * V​e​r​i​f​i​e​d​ ​B​u​s​i​n​e​s​s
		 */
		verifiedBusiness: string
	}
	paymentButton: {
		/**
		 * R​e​c​u​r​r​i​n​g
		 */
		Recurring: string
		/**
		 * v​i​a
		 */
		via: string
	}
	common: {
		dates: {
			/**
			 * D​a​y
			 */
			day: string
			/**
			 * D​a​y​s
			 */
			days: string
		}
		recurring: {
			/**
			 * d
			 */
			day: string
			/**
			 * w
			 */
			week: string
			/**
			 * m
			 */
			month: string
			/**
			 * y
			 */
			year: string
		}
	}
}

export type TranslationFunctions = {
	walletCard: {
		/**
		 * Custom amount
		 */
		customAmount: () => LocalizedString
		/**
		 * Tap
		 */
		tap: () => LocalizedString
		/**
		 * Scan
		 */
		scan: () => LocalizedString
		/**
		 * here to
		 */
		hereTo: () => LocalizedString
		/**
		 * with Cash
		 */
		withCash: () => LocalizedString
		/**
		 * via
		 */
		via: () => LocalizedString
		/**
		 * Expires in
		 */
		expiresIn: () => LocalizedString
		/**
		 * for
		 */
		'for': () => LocalizedString
		/**
		 * No payment
		 */
		noPayment: () => LocalizedString
		/**
		 * Expired
		 */
		expired: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Switch mode
		 */
		switchMode: () => LocalizedString
		/**
		 * Navigate
		 */
		navigate: () => LocalizedString
		/**
		 * Donate
		 */
		donate: () => LocalizedString
		/**
		 * Pay
		 */
		pay: () => LocalizedString
		/**
		 * payment
		 */
		payment: () => LocalizedString
		/**
		 * Pay
		 */
		purposePay: () => LocalizedString
		/**
		 * Donate
		 */
		purposeDonate: () => LocalizedString
		/**
		 * Verified Business
		 */
		verifiedBusiness: () => LocalizedString
	}
	paymentButton: {
		/**
		 * Recurring
		 */
		Recurring: () => LocalizedString
		/**
		 * via
		 */
		via: () => LocalizedString
	}
	common: {
		dates: {
			/**
			 * Day
			 */
			day: () => LocalizedString
			/**
			 * Days
			 */
			days: () => LocalizedString
		}
		recurring: {
			/**
			 * d
			 */
			day: () => LocalizedString
			/**
			 * w
			 */
			week: () => LocalizedString
			/**
			 * m
			 */
			month: () => LocalizedString
			/**
			 * y
			 */
			year: () => LocalizedString
		}
	}
}

export type Formatters = {}
