// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'cs_CZ'
	| 'de'
	| 'en'
	| 'es'
	| 'fa_IR'
	| 'fr'
	| 'hi_IN'
	| 'hu'
	| 'it'
	| 'ja'
	| 'ko_KR'
	| 'pl'
	| 'pt_BR'
	| 'ru'
	| 'sk'
	| 'th'
	| 'tl_PH'
	| 'tr'
	| 'vi_VN'
	| 'zh_CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	walletCard: {
		/**
		 * C​u​s​t​o​m​ ​a​m​o​u​n​t
		 */
		customAmount: string
		/**
		 * T​a​p
		 */
		tap: string
		/**
		 * S​c​a​n
		 */
		scan: string
		/**
		 * h​e​r​e​ ​t​o
		 */
		hereTo: string
		/**
		 * w​i​t​h​ ​C​a​s​h
		 */
		withCash: string
		/**
		 * v​i​a
		 */
		via: string
		/**
		 * E​x​p​i​r​e​s​ ​i​n
		 */
		expiresIn: string
		/**
		 * f​o​r
		 */
		'for': string
		/**
		 * N​o​ ​p​a​y​m​e​n​t
		 */
		noPayment: string
		/**
		 * E​x​p​i​r​e​d
		 */
		expired: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * S​w​i​t​c​h​ ​m​o​d​e
		 */
		switchMode: string
		/**
		 * N​a​v​i​g​a​t​e
		 */
		navigate: string
		/**
		 * D​o​n​a​t​e
		 */
		donate: string
		/**
		 * P​a​y
		 */
		pay: string
		/**
		 * p​a​y​m​e​n​t
		 */
		payment: string
		/**
		 * P​a​y
		 */
		purposePay: string
		/**
		 * D​o​n​a​t​e
		 */
		purposeDonate: string
		/**
		 * V​e​r​i​f​i​e​d​ ​B​u​s​i​n​e​s​s
		 */
		verifiedBusiness: string
		/**
		 * V​e​r​i​f​i​e​d​ ​W​e​b​s​i​t​e
		 */
		verifiedWebsite: string
	}
	paymentButton: {
		/**
		 * R​e​c​u​r​r​i​n​g
		 */
		Recurring: string
		/**
		 * v​i​a
		 */
		via: string
	}
	common: {
		dates: {
			/**
			 * D​a​y
			 */
			day: string
			/**
			 * D​a​y​s
			 */
			days: string
		}
		recurring: {
			/**
			 * d
			 */
			day: string
			/**
			 * w
			 */
			week: string
			/**
			 * m
			 */
			month: string
			/**
			 * y
			 */
			year: string
		}
	}
	paypass: {
		/**
		 * A​c​c​o​u​n​t​ ​A​d​d​r​e​s​s
		 */
		address: string
		/**
		 * N​e​t​w​o​r​k
		 */
		network: string
		/**
		 * C​a​s​h
		 */
		cash: string
		/**
		 * C​h​a​i​n
		 */
		chain: string
		/**
		 * A​m​o​u​n​t
		 */
		amount: string
		/**
		 * I​t​e​m
		 */
		purpose: string
		/**
		 * R​e​c​u​r​r​i​n​g​ ​D​o​n​a​t​i​o​n
		 */
		recurringDonation: string
		/**
		 * R​e​c​u​r​r​i​n​g​ ​P​a​y​m​e​n​t
		 */
		recurringPayment: string
		/**
		 * D​o​n​a​t​i​o​n
		 */
		donation: string
		/**
		 * P​a​y​m​e​n​t
		 */
		payment: string
		/**
		 * S​w​a​p​ ​f​o​r
		 */
		swapFor: string
		/**
		 * S​p​l​i​t
		 */
		split: string
		/**
		 * I​B​A​N
		 */
		iban: string
		/**
		 * B​I​C
		 */
		bic: string
		/**
		 * B​e​n​e​f​i​c​i​a​r​y
		 */
		beneficiary: string
		/**
		 * B​I​C​ ​/​ ​O​R​I​C
		 */
		bicOroric: string
		/**
		 * A​c​c​o​u​n​t​ ​N​u​m​b​e​r
		 */
		accountNumber: string
		/**
		 * R​o​u​t​i​n​g​ ​N​u​m​b​e​r
		 */
		routingNumber: string
		/**
		 * A​c​c​o​u​n​t​ ​A​l​i​a​s
		 */
		accountAlias: string
		/**
		 * M​e​s​s​a​g​e
		 */
		message: string
		/**
		 * I​D
		 */
		id: string
		/**
		 * A​c​c​o​u​n​t​ ​I​D
		 */
		accountId: string
		/**
		 * P​a​y
		 */
		pay: string
		/**
		 * P​a​y​P​a​s​s
		 */
		paypass: string
		/**
		 * S​c​a​n​ ​t​o​ ​d​o​n​a​t​e
		 */
		scanToDonate: string
		/**
		 * S​c​a​n​ ​t​o​ ​p​a​y
		 */
		scanToPay: string
		/**
		 * P​a​y​m​e​n​t​ ​L​o​c​a​t​i​o​n
		 */
		paymentLocation: string
		/**
		 * N​a​v​i​g​a​t​e​ ​t​o​ ​L​o​c​a​t​i​o​n
		 */
		navigateToLocation: string
		/**
		 * V​i​e​w​ ​T​r​a​n​s​a​c​t​i​o​n​s
		 */
		viewTransactions: string
		/**
		 * O​n​l​i​n​e​ ​P​a​y​P​a​s​s
		 */
		onlinePaypass: string
		/**
		 * T​o​p​ ​u​p​ ​C​r​y​p​t​o​C​a​r​d
		 */
		topUpCryptoCard: string
		/**
		 * S​w​a​p​ ​C​u​r​r​e​n​c​y
		 */
		swapCurrency: string
		/**
		 * A​c​t​i​v​a​t​e​ ​P​r​o
		 */
		activatePro: string
		/**
		 * S​e​n​d​ ​O​f​f​l​i​n​e​ ​T​r​a​n​s​a​c​t​i​o​n
		 */
		sendOfflineTransaction: string
	}
}

export type TranslationFunctions = {
	walletCard: {
		/**
		 * Custom amount
		 */
		customAmount: () => LocalizedString
		/**
		 * Tap
		 */
		tap: () => LocalizedString
		/**
		 * Scan
		 */
		scan: () => LocalizedString
		/**
		 * here to
		 */
		hereTo: () => LocalizedString
		/**
		 * with Cash
		 */
		withCash: () => LocalizedString
		/**
		 * via
		 */
		via: () => LocalizedString
		/**
		 * Expires in
		 */
		expiresIn: () => LocalizedString
		/**
		 * for
		 */
		'for': () => LocalizedString
		/**
		 * No payment
		 */
		noPayment: () => LocalizedString
		/**
		 * Expired
		 */
		expired: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Switch mode
		 */
		switchMode: () => LocalizedString
		/**
		 * Navigate
		 */
		navigate: () => LocalizedString
		/**
		 * Donate
		 */
		donate: () => LocalizedString
		/**
		 * Pay
		 */
		pay: () => LocalizedString
		/**
		 * payment
		 */
		payment: () => LocalizedString
		/**
		 * Pay
		 */
		purposePay: () => LocalizedString
		/**
		 * Donate
		 */
		purposeDonate: () => LocalizedString
		/**
		 * Verified Business
		 */
		verifiedBusiness: () => LocalizedString
		/**
		 * Verified Website
		 */
		verifiedWebsite: () => LocalizedString
	}
	paymentButton: {
		/**
		 * Recurring
		 */
		Recurring: () => LocalizedString
		/**
		 * via
		 */
		via: () => LocalizedString
	}
	common: {
		dates: {
			/**
			 * Day
			 */
			day: () => LocalizedString
			/**
			 * Days
			 */
			days: () => LocalizedString
		}
		recurring: {
			/**
			 * d
			 */
			day: () => LocalizedString
			/**
			 * w
			 */
			week: () => LocalizedString
			/**
			 * m
			 */
			month: () => LocalizedString
			/**
			 * y
			 */
			year: () => LocalizedString
		}
	}
	paypass: {
		/**
		 * Account Address
		 */
		address: () => LocalizedString
		/**
		 * Network
		 */
		network: () => LocalizedString
		/**
		 * Cash
		 */
		cash: () => LocalizedString
		/**
		 * Chain
		 */
		chain: () => LocalizedString
		/**
		 * Amount
		 */
		amount: () => LocalizedString
		/**
		 * Item
		 */
		purpose: () => LocalizedString
		/**
		 * Recurring Donation
		 */
		recurringDonation: () => LocalizedString
		/**
		 * Recurring Payment
		 */
		recurringPayment: () => LocalizedString
		/**
		 * Donation
		 */
		donation: () => LocalizedString
		/**
		 * Payment
		 */
		payment: () => LocalizedString
		/**
		 * Swap for
		 */
		swapFor: () => LocalizedString
		/**
		 * Split
		 */
		split: () => LocalizedString
		/**
		 * IBAN
		 */
		iban: () => LocalizedString
		/**
		 * BIC
		 */
		bic: () => LocalizedString
		/**
		 * Beneficiary
		 */
		beneficiary: () => LocalizedString
		/**
		 * BIC / ORIC
		 */
		bicOroric: () => LocalizedString
		/**
		 * Account Number
		 */
		accountNumber: () => LocalizedString
		/**
		 * Routing Number
		 */
		routingNumber: () => LocalizedString
		/**
		 * Account Alias
		 */
		accountAlias: () => LocalizedString
		/**
		 * Message
		 */
		message: () => LocalizedString
		/**
		 * ID
		 */
		id: () => LocalizedString
		/**
		 * Account ID
		 */
		accountId: () => LocalizedString
		/**
		 * Pay
		 */
		pay: () => LocalizedString
		/**
		 * PayPass
		 */
		paypass: () => LocalizedString
		/**
		 * Scan to donate
		 */
		scanToDonate: () => LocalizedString
		/**
		 * Scan to pay
		 */
		scanToPay: () => LocalizedString
		/**
		 * Payment Location
		 */
		paymentLocation: () => LocalizedString
		/**
		 * Navigate to Location
		 */
		navigateToLocation: () => LocalizedString
		/**
		 * View Transactions
		 */
		viewTransactions: () => LocalizedString
		/**
		 * Online PayPass
		 */
		onlinePaypass: () => LocalizedString
		/**
		 * Top up CryptoCard
		 */
		topUpCryptoCard: () => LocalizedString
		/**
		 * Swap Currency
		 */
		swapCurrency: () => LocalizedString
		/**
		 * Activate Pro
		 */
		activatePro: () => LocalizedString
		/**
		 * Send Offline Transaction
		 */
		sendOfflineTransaction: () => LocalizedString
	}
}

export type Formatters = {}
