// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

const localeTranslationLoaders = {
	ar: () => import('./ar'),
	cs_CZ: () => import('./cs_CZ'),
	de: () => import('./de'),
	en: () => import('./en'),
	es: () => import('./es'),
	fa_IR: () => import('./fa_IR'),
	fr: () => import('./fr'),
	hi_IN: () => import('./hi_IN'),
	hu: () => import('./hu'),
	it: () => import('./it'),
	ja: () => import('./ja'),
	ko_KR: () => import('./ko_KR'),
	pl: () => import('./pl'),
	pt_BR: () => import('./pt_BR'),
	ru: () => import('./ru'),
	sk: () => import('./sk'),
	th: () => import('./th'),
	tl_PH: () => import('./tl_PH'),
	tr: () => import('./tr'),
	vi_VN: () => import('./vi_VN'),
	zh_CN: () => import('./zh_CN'),
}

const updateDictionary = (locale: Locales, dictionary: Partial<Translations>): Translations =>
	loadedLocales[locale] = { ...loadedLocales[locale], ...dictionary }

export const importLocaleAsync = async (locale: Locales): Promise<Translations> =>
	(await localeTranslationLoaders[locale]()).default as unknown as Translations

export const loadLocaleAsync = async (locale: Locales): Promise<void> => {
	updateDictionary(locale, await importLocaleAsync(locale))
	loadFormatters(locale)
}

export const loadAllLocalesAsync = (): Promise<void[]> => Promise.all(locales.map(loadLocaleAsync))

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
