export const ASSETS_NAMES: Record<string, string> = {
	"1INCH": "1inch",
	"AAVE": "Aave",
	"ADA": "Cardano",
	"ALGO": "Algorand",
	"ANKR": "Ankr",
	"APT": "Aptos",
	"ARB": "Arbitrum",
	"ATOM": "Cosmos",
	"AVAX": "Avalanche",
	"AXS": "Axie Infinity",
	"BAL": "Balancer",
	"BAT": "Basic Attention Token",
	"BCH": "Bitcoin Cash",
	"BNB": "BNB",
	"BTC": "Bitcoin",
	"BGB": "Bitget Token",
	"CELO": "Celo",
	"CHZ": "Chiliz",
	"COMP": "Compound",
	"CRO": "Cronos",
	"CRV": "Curve DAO Token",
	"DAI": "Dai",
	"DEXE": "DeXe",
	"DGB": "DigiByte",
	"DOGE": "Dogecoin",
	"DOT": "Polkadot",
	"EGLD": "MultiversX",
	"ENA": "Ethena",
	"ETC": "Ethereum Classic",
	"ETH": "Ethereum",
	"EURC": "EUR Coin",
	"FDUSD": "First Digital USD",
	"FIL": "Filecoin",
	"FET": "Artificial Superintelligence Alliance",
	"FXS": "Frax Share",
	"GALA": "Gala",
	"GT": "GateToken",
	"GRT": "The Graph",
	"HBAR": "Hedera",
	"HYPE": "Hyperliquid",
	"ICP": "Internet Computer",
	"ICX": "ICON",
	"IMX": "Immutable",
	"INJ": "Injective",
	"IOST": "IOST",
	"JUP": "Jupiter",
	"KAS": "Kaspa",
	"KAVA": "Kava",
	"KCS": "KuCoin Token",
	"KNC": "Kyber Network Crystal",
	"LDO": "Lido DAO",
	"LEO": "UNUS SED LEO",
	"LINK": "Chainlink",
	"LRC": "Loopring",
	"LTC": "Litecoin",
	"MKR": "Maker",
	"MNT": "Mantle",
	"NEAR": "NEAR Protocol",
	"OM": "MANTRA",
	"OKB": "OKB",
	"ONDO": "Ondo",
	"ONT": "Ontology",
	"OP": "Optimism",
	"PEPE": "Pepe",
	"POL": "POL",
	"QNT": "Quant",
	"RAY": "Raydium",
	"REN": "Ren",
	"RENDER": "Render",
	"RNDR": "Render Token",
	"ROSE": "Oasis Network",
	"SC": "Siacoin",
	"SHIB": "Shiba Inu",
	"SOL": "Solana",
	"SUI": "Sui",
	"SAND": "The Sandbox",
	"STORJ": "Storj",
	"STX": "Stacks",
	"TAO": "Bittensor",
	"THETA": "Theta Network",
	"TIA": "Celestia",
	"TRX": "TRON",
	"TWT": "Trust Wallet Token",
	"TRUMP": "OFFICIAL TRUMP",
	"UNI": "Uniswap",
	"USDC": "USD Coin",
	"USDT": "Tether USD",
	"USDe": "Ethena USDe",
	"USDX": "Core USD",
	"VET": "VeChain",
	"WAVES": "Waves",
	"XAB": "Core Testnet",
	"XCB": "Core",
	"XCE": "Core Enterprise",
	"XDC": "XDC Network",
	"XLM": "Stellar",
	"XMR": "Monero",
	"XRP": "XRP",
	"YFI": "yearn.finance",
	"ZEN": "Horizen",
	"ZIL": "Zilliqa"
}
